Add utility function to compute/check ZIM descriptions
openzim/python-scraperlib pull request #111
Opened 2023-08-21 14:16 UTC by benoit74

Fix #110 

Changes:
- new utility function `compute_descriptions` in `inputs.py` to compute ZIM-compliant descriptions based on default and user-provided values

2023-08-21 16:04 UTC, rgaudin requested changes
Works as expected ; thank you but this new `Descriptions` class is uncalled for. We don't want to extend the API surface which such a thing. I believe returning a tuple here is appropriate.

2023-08-22 08:11 UTC, rgaudin approved these changes

2023-08-22 13:16 UTC, benoit74 commented
It's ok for me, and I've added my CHANGELOG.
I let you merge since I can't 😆

2023-08-22 13:37 UTC, rgaudin approved these changes

2023-08-22 13:38 UTC, merged