Drop disallowed control characters and strip blank characters
openzim/python-scraperlib pull request #179
Opened 2024-07-10 14:32 UTC by benoit74

Fix #159 

- Automatically drop all control characters in metadata except `\r`, `\n` and `\t`
- Automatically strip blank characters ` `, `\r`, `\n` and `\t` in metadata

2024-07-26 11:35 UTC, rgaudin requested changes
Minor details ; please add abn entry in the CHANGELOG as well

2024-07-26 11:35 UTC, rgaudin commented on src/zimscraperlib/zim/creator.py
> +        for k, v in self._metadata.items():
Single char variables are evil 😉

2024-07-26 11:35 UTC, rgaudin commented on src/zimscraperlib/zim/creator.py
> +CONTROL_CHARACTERS_REGEX = regex.compile(r"(?![\n\t\r])\p{C}")
```suggestion
UNWANTED_CONTROL_CHARACTERS_REGEX = regex.compile(r"(?![\n\t\r])\p{C}")
```

2024-07-26 11:35 UTC, rgaudin commented on src/zimscraperlib/zim/creator.py
> +        if isinstance(content, str):
Why the check? We should `sub` directly

2024-07-29 13:59 UTC, benoit74 commented on src/zimscraperlib/zim/creator.py
> +        for k, v in self._metadata.items():
Agreed

2024-07-29 13:59 UTC, benoit74 commented on src/zimscraperlib/zim/creator.py
> +        if isinstance(content, str):
Agreed

2024-07-29 17:04 UTC, rgaudin approved these changes

2024-07-30 06:17 UTC, merged