Process / return a new typed Lang class in i18n methods
openzim/python-scraperlib pull request #183
Opened 2024-07-30 09:15 UTC by benoit74

Fix #151 

Changes:
-

2024-07-30 15:01 UTC, rgaudin requested changes
Welcomed change!

I see a missed opportunity for a proper type here that's not a wrapper around some dict.
If you're attached to that dict-ness, then subclass dict instead ; that'd be cleaner.

2024-07-30 19:23 UTC, benoit74 commented
The dict-ness is just the least effort path. Code is regularly updating / merging multiple properties at once, and it is a mess / very verbose to re-implement without the dict facilities (see e.g. `update_with_macro` with I don't know how to reimplement with a proper type). Since the main goal was to expose something more useful rather than a problem of maintainability, I considered that dict-ness was the appropriate solution.

That being that, I would also prefer to use a proper type if this does not makes the code too verbose. Shall we use pydantic BaseModel as base class? It would be a new dependency, it would help a bit, even if it would probably not solve all issues

2024-07-30 19:23 UTC, benoit74 commented
(and using a proper type was also my initial trial, but I quickly realized it was not that convenient to write)

2024-07-31 09:20 UTC, rgaudin commented
Well I think you did not read my comment to the end and that none of your arguments make sense but given it was late when you replied, I think fresh eyes will have us agree that what I commited is simpler and has no downsides. Revert if that's not the case. I only tested via running the unit tests

2024-08-02 07:56 UTC, benoit74 commented
I did read it, just I'm not that attached to `dict`, and as said I would have preferred to use a proper type that does not subclass `dict`.

Let's go with `dict`, I will learn how to do it with a proper type next time (and maybe it is just not "wishable"), I like your simplification anyway.

I'll just replace `dict` by `Dict` to prepare for the future.

2024-08-02 08:00 UTC, benoit74 commented on CHANGELOG.md
> +- **BREAKING** Rename `i18.NotFound` to `i18n.NotFoundError`
Done

2024-08-02 08:02 UTC, benoit74 commented
Edit: ~~I'll just replace dict by Dict to prepare for the future~~ `dict` is already the future ^^

2024-08-02 08:19 UTC, rgaudin approved these changes

2024-08-02 09:22 UTC, merged